### ISSUE TITLE
The Furnace's Advanced Macros are breaking some chat macros (particularly Sky's Powercards module)

### ISSUE THREAD

**Issue by Norc** [kakaroto/fvtt-module-furnace#49]
Test Info (latest everything): Foundry 0.6.0 on Windows 10 self hosted (electron app as GM), DND5e 0.92, Powercards 0.0.7, Furnace 1.8.

I am attempting to use Sky's not-officially-distributed Powercard's module (https://github.com/Sky-Captain-13/foundry/tree/master/powercards). When a specially formatted chat macro (not script) is run, it generates a shiny powercard for the output:

```
!power {{
--emote|Surprise, MFer.
--title|Surprise
--title_fontsize|1.5em
--title_txcolor|#FFFFFF
--title_bgcolor|#8B0000
--subtitle|Ranged * Range (80/320)
--Attack:|[[1d20 + 4]] | [[1d20 + 4]] vs AC
--Damage:|[[2d6+6d6+4]] critical hit piercing damage
}}
```
Is supposed to turn into this in the Chat Log:

![image](https://user-images.githubusercontent.com/64667579/83282921-53c1aa00-a1a8-11ea-80c7-2a1b4e860e8d.png)

Without The Furnace's advanced macros enabled, this works as intended. However, if I check the Advanced Macros configuration, I instead get this error for the same macro:

![image](https://user-images.githubusercontent.com/64667579/83283502-51138480-a1a9-11ea-9326-8b38926215bf.png)

After talking with Sky, he's indicated that it's out of the scope of his module to fix this issue.

I have two questions for you: 

1) Is the Advanced Macros supposed to be parsing chat macros at all?
2) If it is, is it possible for The Furnace to not parse any chat macros that start with "!power"?
3) Is it possible to rewrite that Powercard macro in a way that The Furnace will not hate it?

Thanks!! Any help would be greatly appreciated :(

**Comment by kakaroto** [comment]
1. Yes, see : https://github.com/kakaroto/fvtt-module-furnace#advanced-macros

> In the case of chat macros, you can now use handlebars templating to render your chat text using common helpers, or use it along with the macro helper to call other macros, like for example `{{macro "name of my macro" actor 3 "a text argument"}}`

The issue is that he's using `{{ }}` for his powercards which are handlebar's special characters. This is of course causing the error, and there is no way around it.

2. No, because with the ~200 modules out there, there is bound to be some incompatibilities and just keeping track of what everyone is doing and adding special use cases for anyone who decides to do things differently, is going to be a full time job. I do not want to start adding special use cases for one module, because it would mean having to add special use cases for any other module that breaks things, or to start showing favoritism.

3. I don't think so. I'd consider the two features as incompatible.

Note: I've spoken about Sky's powercards back in August last year, I actually added the first iterations of the macros (before they existed in the core foundry) months ago with the specific use of the handlebar templates and spoken to Sky multiple times about the design and how he could use the handlebar syntax to build his power cards for Foundry. He isn't using that design, probably because he wants the power cards to have the exact same syntax as they had on Roll20 and it's incompatible because of that.

**Comment by Norc** [comment]
Good news. I got a tip from @Rücklicht (Frerk)#0985 on the Foundry discord. Replacing the {{ }} with a single bracket set {} still works in Powercards, and no longer runs afoul of The Furnace. Closing my issue, thanks for the response!

And I totally hear you on the module incompatibilities...

**Comment by kakaroto** [comment]
That's great to hear! And thanks for letting me know, I'll be sure to tell others that using a single `{ }` works as well if they have the same issue.
Thanks!
