### ISSUE TITLE
Improved Web Fonts support

### ISSUE THREAD

**Issue by apoapostolov** [kakaroto/fvtt-module-furnace#50]
Is it possible to add interface for registering web fonts from Google for use in the font dialog in the drawing tool. The idea is to be able to use a lot more font, especially decorative ones, rather than the few serif or non-serif classic options in the platform today.

**Comment by kakaroto** [comment]
It was planned to add more font options, but never done due to lack of time. I wanted however to keep it specifically set to only show 'web safe fonts' though.

Regardless, Furnace uses the fonts that are added to Foundry as it already has an API for adding fonts to it. I don't know if there is another module that allows addition of custom fonts (there should be I think, I know you're not the first to want such a thing), but if you have a different font added to foundry through other means, Furnace will already pick those up and show them as available options.

**Comment by Ryex** [comment]
Furnace does seem to be missing fonts that are useable when the drawing tools are disabled

With Furnace I can see
* Arial
* Arial black
* Comic Sans MS
* Couier New

With the drawing tools disabled I can also pick
* Signika
* Modesto Condensed

To be fair, Modesto was only just packed with 0.6.4

**Comment by kakaroto** [comment]
@Ryex 0.6.4 changed the API for loading fonts and for where the list of fonts that Foundry supports is stored. This is why it doesn't show those anymore. I'm fixing it now.
Also going to close this as I think it's not clear that a font manager is outside the scope of Furnace. If any module does load fonts and adds them properly to foundry's config, then Furnace will be able to use them.
