### ISSUE TITLE
0.7.6 Drawing Tools can't close with Furnace active

### ISSUE THREAD

**Issue by frvwfr2** [kakaroto/fvtt-module-furnace#84]
With Furnace active, the Drawing Tools config no longer is able to close.

**Comment by velara** [comment]
Dice so nice was effected by the same issue. And they've found the fix. Their herited FormApplication wasn't closing anymore on a submit since 0.7.6. It was because their override of the "close" method wasn't passing the parameters and 0.7.6 introduced a new option that was needed in this case (the "force" option). Thanks to JDW for figuring the issue out.

To be specific the drawing tools config should be able to close, until you use the update/save button after which point the close button will no longer function.

**Comment by amcvfx** [comment]
I am assuming a fix for this will be on the way? :)

**Comment by kakaroto** [comment]
Thanks for the report and @velara for the passing along of info from JDW's research. (woahhhh, your text **just** changed under my eyes! either you just edited, or I really need to sleep!!!)
Will fix.
Good night!

**Comment by velara** [comment]
Changing lines 191 and 192 of DrawingConfig.js 
to 
  close(options) {
    super.close(options);

Appears to have resolved this issue for me.
